import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { Sky } from 'three/addons/objects/Sky.js';
import './style.css';

const projects = {
  chrono: { id:'chrono', index:'01', type:'PYTHON · AI RETRIEVAL', title:'ChronoWeave', short:'CHRONO WEAVE', description:'Un indice vettoriale estendibile per il retrieval AI: oltre alla similarità semantica, considera freschezza temporale, provenienza dell’evidenza e forza della corroborazione.', tags:['Python','Vector index','RAG','Evidence-aware'], link:'https://github.com/antofallea/ChronoWeave', position:new THREE.Vector3(18,0,-13), color:0xff7856 },
  ris: { id:'ris', index:'02', type:'PYTHON · GRAPH DATA', title:'Relational Identity Structure', short:'R.I.S. LAB', description:'Un prototipo per rappresentare l’identità delle entità attraverso firme relazionali. Unisce grafi tipizzati, record linkage e un benchmark riproducibile.', tags:['Python','Entity resolution','Graphs','Research'], link:'https://github.com/antofallea/relational-identity-structure', position:new THREE.Vector3(-19,0,14), color:0xc8ef5b },
};
const infoPlace = { id: 'info', short: 'INFO HOUSE', position: new THREE.Vector3(-10, 0, -11) };

const canvas=document.querySelector('#world'), scene=new THREE.Scene(), clock=new THREE.Clock();
scene.background=new THREE.Color('#7199ab'); scene.fog=new THREE.FogExp2('#7199ab',.018);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,180);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=.9; renderer.outputColorSpace=THREE.SRGBColorSpace;
const composer=new EffectComposer(renderer); composer.addPass(new RenderPass(scene,camera)); composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.08,.25,.99));
const world=new THREE.Group(); scene.add(world);
const colliders=[], hubs=[], clickables=[], cars=[], particles=[];
const material={
  concrete:new THREE.MeshStandardMaterial({color:'#879da2',roughness:.88}), pavement:new THREE.MeshStandardMaterial({color:'#c9cac2',roughness:.77}), asphalt:new THREE.MeshStandardMaterial({color:'#263b46',roughness:.6,metalness:.16}), paint:new THREE.MeshStandardMaterial({color:'#edeadf',roughness:.5}), navy:new THREE.MeshStandardMaterial({color:'#0a2033',roughness:.67,metalness:.12}), glass:new THREE.MeshPhysicalMaterial({color:'#76b1c4',roughness:.14,metalness:.28,transmission:.05,clearcoat:.6}), foliage:new THREE.MeshStandardMaterial({color:'#496f60',roughness:1}), trunk:new THREE.MeshStandardMaterial({color:'#3b4540',roughness:1}), orange:new THREE.MeshStandardMaterial({color:'#f07855',roughness:.5,emissive:'#bd3d25',emissiveIntensity:.26}), lime:new THREE.MeshStandardMaterial({color:'#c8ef5b',roughness:.66,emissive:'#8aaf26',emissiveIntensity:.2}), light:new THREE.MeshStandardMaterial({color:'#fff0c8',emissive:'#ffc66b',emissiveIntensity:3.1}),
};
scene.add(new THREE.HemisphereLight('#caebf4','#132a37',2.2));
const sun=new THREE.DirectionalLight('#e9f2f5',1.35); sun.position.set(24,34,12); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); Object.assign(sun.shadow.camera,{left:-43,right:43,top:43,bottom:-43}); scene.add(sun);
const glow=new THREE.PointLight('#f1ab73',4,27,2); glow.position.set(0,11,0); scene.add(glow);
const sky=new Sky(); sky.scale.setScalar(450000); scene.add(sky); Object.assign(sky.material.uniforms,{turbidity:{value:7.5},rayleigh:{value:1.7},mieCoefficient:{value:.008},mieDirectionalG:{value:.78}}); sky.material.uniforms.sunPosition.value.set(0.3,0.65,-.5).normalize();
function groundTexture(base,variance,repeat){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d'),rgb=base.match(/\w\w/g).map(v=>parseInt(v,16));const img=x.createImageData(512,512);for(let i=0;i<img.data.length;i+=4){const n=(Math.random()-.5)*variance;img.data[i]=rgb[0]+n;img.data[i+1]=rgb[1]+n;img.data[i+2]=rgb[2]+n;img.data[i+3]=255}x.putImageData(img,0,0);x.globalAlpha=.16;x.strokeStyle='#0a151a';for(let i=0;i<45;i++){x.beginPath();x.moveTo(Math.random()*512,Math.random()*512);x.lineTo(Math.random()*512,Math.random()*512);x.stroke()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(repeat,repeat);return t}
material.asphalt.map=groundTexture('263b46',24,9);material.concrete.map=groundTexture('879da2',32,11);material.pavement.map=groundTexture('c9cac2',18,8);Object.values(material).forEach(m=>m.needsUpdate=true);

function create(geometry,mat,x=0,y=0,z=0,parent=world){const o=new THREE.Mesh(geometry,mat);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
function box(w,h,d,x,y,z,mat,parent=world){return create(new THREE.BoxGeometry(w,h,d),mat,x,y+h/2,z,parent)}
function cylinder(r,h,x,y,z,mat,parent=world){return create(new THREE.CylinderGeometry(r,r,h,18),mat,x,y+h/2,z,parent)}
function collide(x,z,w,d){colliders.push({x,z,w:w/2+.7,d:d/2+.7})}
function label(text,color='#0a2033'){const c=document.createElement('canvas');c.width=900;c.height=160;const x=c.getContext('2d');x.font='600 48px \"DM Mono\", monospace';x.textAlign='center';x.textBaseline='middle';x.lineJoin='round';x.lineWidth=18;x.strokeStyle=color;x.strokeText(text,450,80);x.fillStyle='#f5f1e6';x.fillText(text,450,80);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(7.4,1.32,1);return s}
function road(w,d,x,z){box(w,.035,d,x,0,z,material.asphalt).castShadow=false;const horiz=w>d;for(let p=-Math.max(w,d)/2+2;p<Math.max(w,d)/2;p+=4.2){const dash=box(horiz?1.7:.16,.045,horiz?.16:1.7,horiz?x+p:x,.04,horiz?z:z+p,material.paint);dash.castShadow=false}}
function tree(x,z,s=1){const g=new THREE.Group(),t=create(new THREE.CylinderGeometry(.14*s,.2*s,1.35*s,8),material.trunk,0,.67*s,0,g),c=create(new THREE.IcosahedronGeometry(.95*s,2),material.foliage,0,1.8*s,0,g);t.castShadow=c.castShadow=true;c.scale.y=1.15;g.position.set(x,0,z);world.add(g)}
function lamp(x,z){const g=new THREE.Group();create(new THREE.CylinderGeometry(.055,.075,3.1,8),material.navy,0,1.55,0,g);create(new THREE.BoxGeometry(.48,.16,.48),material.light,0,3.12,0,g);g.position.set(x,0,z);world.add(g)}
function bench(x,z,r=0){const g=new THREE.Group(),wood=new THREE.MeshStandardMaterial({color:'#9c6d49',roughness:.8});create(new THREE.BoxGeometry(1.55,.12,.44),wood,0,.7,0,g);create(new THREE.BoxGeometry(1.55,.55,.1),wood,0,1,-.18,g);[-.55,.55].forEach(s=>create(new THREE.BoxGeometry(.09,.7,.28),material.navy,s,.35,0,g));g.position.set(x,0,z);g.rotation.y=r;world.add(g)}
function infoHouse(){const g=new THREE.Group();g.position.copy(infoPlace.position);const pad=create(new THREE.BoxGeometry(7.2,.2,6.7),material.pavement,0,.1,0,g),walls=create(new THREE.BoxGeometry(5.8,3.8,5.25),new THREE.MeshStandardMaterial({color:'#e3ded1',roughness:.86}),0,1.9,0,g),roof=create(new THREE.ConeGeometry(4.6,2.75,4),material.orange,0,5.17,0,g);roof.rotation.y=Math.PI/4;walls.castShadow=roof.castShadow=true;create(new THREE.BoxGeometry(1.15,2.1,.12),material.navy,0,1.12,2.7,g);[-1.75,1.75].forEach(x=>{const w=create(new THREE.BoxGeometry(1.05,1.1,.13),material.light,x,2.25,2.7,g);w.material=new THREE.MeshStandardMaterial({color:'#b5e7f0',emissive:'#95d7ef',emissiveIntensity:1.8})});create(new THREE.BoxGeometry(.75,2.1,.75),material.navy,1.85,5.6,-1.45,g);const sign=label('INFO HOUSE','#0a2033');sign.position.y=7.5;g.add(sign);g.userData={place:infoPlace};clickables.push(g);world.add(g);collide(infoPlace.position.x,infoPlace.position.z,6.2,5.7)}
function building(x,z,w,d,h,v=0){const g=new THREE.Group();g.position.set(x,0,z);const body=create(new THREE.BoxGeometry(w,h,d),v%3===0?material.glass:material.navy,0,h/2,0,g),roof=create(new THREE.BoxGeometry(w+.35,.22,d+.35),v%2?material.concrete:material.orange,0,h+.11,0,g);body.castShadow=roof.castShadow=true;for(let y=1.1;y<h-.25;y+=1.25)create(new THREE.BoxGeometry(w+.04,.055,d+.04),material.concrete,0,y,0,g);if(v%2===0)create(new THREE.CylinderGeometry(.055,.055,1.6,8),material.navy,0,h+.9,0,g);world.add(g);collide(x,z,w,d)}
function car(x,z,color,dir=1,move=false){const g=new THREE.Group(),coat=new THREE.MeshStandardMaterial({color,roughness:.32,metalness:.55});create(new THREE.BoxGeometry(1.45,.45,2.7),coat,0,.54,0,g);create(new THREE.BoxGeometry(1.2,.55,1.35),material.glass,0,.98,-.1,g);[-.59,.59].forEach(side=>[-.82,.82].forEach(front=>{const w=create(new THREE.CylinderGeometry(.25,.25,.17,12),material.navy,side,.32,front,g);w.rotation.z=Math.PI/2}));g.position.set(x,0,z);g.rotation.y=dir===1?0:Math.PI;world.add(g);if(move)cars.push({g,dir,phase:x/20})}
function projectHub(project,type){const g=new THREE.Group();g.position.copy(project.position);const pad=create(new THREE.CylinderGeometry(5.2,5.2,.22,48),material.pavement,0,.11,0,g),ring=create(new THREE.TorusGeometry(4.16,.09,12,48),type==='chrono'?material.orange:material.lime,0,.25,0,g);ring.rotation.x=Math.PI/2;if(type==='chrono'){create(new THREE.BoxGeometry(4.2,9.2,4.2),material.glass,0,4.6,0,g);for(let y=1.1;y<9.1;y+=1.16)create(new THREE.BoxGeometry(4.32,.08,4.32),material.navy,0,y,0,g);create(new THREE.BoxGeometry(4.62,.42,4.62),material.orange,0,9.35,0,g)}else{create(new THREE.CylinderGeometry(3.28,3.28,2.65,12),material.glass,0,1.33,0,g);create(new THREE.SphereGeometry(2.72,32,16,0,Math.PI*2,0,Math.PI/2),material.lime,0,2.62,0,g);for(let i=0;i<6;i++)create(new THREE.BoxGeometry(.55,5.5,.55),material.navy,Math.cos(i*Math.PI/3)*3.05,2.75,Math.sin(i*Math.PI/3)*3.05,g)}const bmat=new THREE.MeshBasicMaterial({color:project.color,transparent:true,opacity:.15,side:THREE.DoubleSide,depthWrite:false}),beam=create(new THREE.CylinderGeometry(.26,1.25,16,20,1,true),bmat,0,8,0,g),orb=create(new THREE.IcosahedronGeometry(.54,2),new THREE.MeshStandardMaterial({color:project.color,emissive:project.color,emissiveIntensity:2.6}),0,15.75,0,g),text=label(project.short,type==='chrono'?'#b8442d':'#6c9024');text.position.y=12.3;g.add(text);g.userData={project,beam,orb};hubs.push(g);clickables.push(g);world.add(g);collide(project.position.x,project.position.z,6.2,6.2)}
function particleField(){const amount=780,p=new Float32Array(amount*3),speed=new Float32Array(amount);for(let i=0;i<amount;i++){p[i*3]=(Math.random()-.5)*78;p[i*3+1]=Math.random()*18+.3;p[i*3+2]=(Math.random()-.5)*78;speed[i]=.25+Math.random()*.55}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(p,3));const point=new THREE.Points(geo,new THREE.PointsMaterial({color:'#fff2c9',size:.065,transparent:true,opacity:.62,depthWrite:false}));scene.add(point);particles.push({point,speed})}

const ground=create(new THREE.PlaneGeometry(88,88),material.concrete);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;
const frame=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(78,.12,78)),new THREE.LineBasicMaterial({color:'#c9e1dd',transparent:true,opacity:.44}));frame.position.y=.06;world.add(frame);
road(78,8,0,0);road(8,78,0,0);road(5.7,34,24,-17);road(34,5.7,-17,24);
const plaza=create(new THREE.CylinderGeometry(8.4,8.4,.09,64),material.pavement,0,.05,0);const plazaRing=create(new THREE.RingGeometry(5.55,5.76,64),new THREE.MeshBasicMaterial({color:'#a8c7c8',side:THREE.DoubleSide}),0,.101,0);plazaRing.rotation.x=-Math.PI/2;
const base=new THREE.Group();create(new THREE.CylinderGeometry(2.85,3.15,1.55,8),material.navy,0,.78,0,base);create(new THREE.ConeGeometry(3.42,2.05,8),material.orange,0,2.55,0,base);const bLabel=label('BASE CAMP');bLabel.position.y=5.65;base.add(bLabel);world.add(base);
infoHouse();
projectHub(projects.chrono,'chrono');projectHub(projects.ris,'ris');
[[-28,-18,5.5,7,5.3,0],[-29,-5,4.5,9,3.6,1],[-18,-29,7,4.6,6.5,2],[16,21,5.2,8,5.1,0],[28,9,5.6,5.5,7.3,1],[27,-25,6.5,5,4.6,2],[-11,28,8,4.4,5,1],[10,-29,7,4.4,4.8,2],[29,-7,4.3,6,6.1,0]].forEach(a=>building(...a));
for(let x=-35;x<=35;x+=5){tree(x,-36,.82);tree(x,35,.85)}for(let z=-30;z<=30;z+=5){tree(-36,z,.76);tree(36,z,.86)}[[-12,11],[11,10],[-10,-12],[11,-10],[-24,19],[22,27],[-26,-27],[26,-4],[-4,24],[20,-6]].forEach(p=>tree(...p,1.2));[-29,-21,-13,13,21,29].forEach(n=>{lamp(n,-4.1);lamp(n,4.1);lamp(-4.1,n);lamp(4.1,n)});bench(-9,9,.4);bench(9,-9,-2.7);bench(-7,-9,1.2);bench(8,9,2.2);car(-24,-1.5,'#de6445',1,true);car(17,1.5,'#d9d5bd',0,true);car(1.5,-19,'#246b8b');car(-1.5,23,'#3b544a',0);particleField();

// Fully modeled, animated avatar: no photo marker.
const player=new THREE.Group(),avatar=new THREE.Group();const shadow=create(new THREE.CircleGeometry(.76,24),new THREE.MeshBasicMaterial({color:'#07111b',transparent:true,opacity:.26}),0,.015,0,player);shadow.rotation.x=-Math.PI/2;
const skin=new THREE.MeshStandardMaterial({color:'#c98961',roughness:.85}),shirt=new THREE.MeshStandardMaterial({color:'#f3f0e8',roughness:.78}),denim=new THREE.MeshStandardMaterial({color:'#4d7184',roughness:.92}),shoe=new THREE.MeshStandardMaterial({color:'#f3f1e8',roughness:.7}),hair=new THREE.MeshStandardMaterial({color:'#17191a',roughness:.95});
create(new THREE.BoxGeometry(.96,1.34,.48),shirt,0,2.72,0,avatar);create(new THREE.CylinderGeometry(.16,.16,.25,12),skin,0,3.52,0,avatar);create(new THREE.SphereGeometry(.42,18,14),skin,0,3.86,0,avatar);create(new THREE.SphereGeometry(.43,18,12,0,Math.PI*2,0,Math.PI*.48),hair,0,4.01,0,avatar);
const legL=new THREE.Group(),legR=new THREE.Group(),armL=new THREE.Group(),armR=new THREE.Group();function limb(group,w,l,mat,y){create(new THREE.BoxGeometry(w,l,w),mat,0,-l/2,0,group);group.position.y=y}
limb(legL,.36,1.28,denim,2.08);limb(legR,.36,1.28,denim,2.08);legL.position.x=-.27;legR.position.x=.27;limb(armL,.27,1.25,shirt,3.2);limb(armR,.27,1.25,shirt,3.2);armL.position.x=-.67;armR.position.x=.67;[-.27,.27].forEach(x=>create(new THREE.BoxGeometry(.42,.24,.66),shoe,x,.18,.13,avatar));avatar.add(legL,legR,armL,armR);avatar.scale.setScalar(.78);player.add(avatar);const pLabel=label('ANTONIO','#0a2033');pLabel.scale.set(3.2,.56,1);pLabel.position.y=4.25;player.add(pLabel);player.position.set(0,.06,6.5);world.add(player);

const state={started:true,destination:null,nearby:null,visited:new Set(),touch:new Set(),cameraYaw:.68,cameraDistance:27,dragging:false,pointerX:0,dragDistance:0},keys=new Set(),target=new THREE.Vector3(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
const zone=document.querySelector('#zoneName'),mission=document.querySelector('#missionText'),prompt=document.querySelector('#interactionPrompt'),nearbyText=document.querySelector('#nearbyName'),mini=document.querySelector('#miniPlayer'),toast=document.querySelector('#toast');
function notify(text){toast.textContent=text;toast.classList.add('visible');setTimeout(()=>toast.classList.remove('visible'),2400)}
function visited(project){if(state.visited.has(project.id))return;state.visited.add(project.id);document.querySelector('#visitedCount').textContent=state.visited.size;notify(`${project.title} discovered`)}
function openProject(project){visited(project);document.querySelector('#dialogIndex').textContent=project.index;document.querySelector('#dialogType').textContent=project.type;document.querySelector('#dialogTitle').textContent=project.title;document.querySelector('#dialogDescription').textContent=project.description;document.querySelector('#dialogTags').innerHTML=project.tags.map(tag=>`<span>${tag}</span>`).join('');document.querySelector('#dialogLink').href=project.link;document.querySelector('#projectDialog').showModal()}
function nearest(){let result=null,d=Infinity;[...Object.values(projects),infoPlace].forEach(p=>{const n=player.position.distanceTo(p.position);if(n<d){result=p;d=n}});return d<6.4?result:null}
function free(pos){return Math.abs(pos.x)<=36&&Math.abs(pos.z)<=36&&!colliders.some(c=>Math.abs(pos.x-c.x)<c.w&&Math.abs(pos.z-c.z)<c.d)}
function updatePlayer(delta){const input=new THREE.Vector3((keys.has('KeyD')||keys.has('ArrowRight')||state.touch.has('right')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')||state.touch.has('left')?1:0),0,(keys.has('KeyS')||keys.has('ArrowDown')||state.touch.has('down')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')||state.touch.has('up')?1:0));let moving=false;if(input.lengthSq()){state.destination=null;moving=true;input.normalize().multiplyScalar(9.25*delta);const n=player.position.clone().add(input);if(free(n))player.position.copy(n);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,Math.atan2(input.x,input.z),.24)}if(state.destination){const d=state.destination.clone().sub(player.position);d.y=0;if(d.length()<.3)state.destination=null;else{moving=true;d.normalize().multiplyScalar(7.8*delta);const n=player.position.clone().add(d);if(free(n)){player.position.copy(n);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,Math.atan2(d.x,d.z),.16)}else state.destination=null}}const t=clock.getElapsedTime(),pace=moving?Math.sin(t*12):Math.sin(t*2)*.04;legL.rotation.x=moving?pace*.78:pace;legR.rotation.x=moving?-pace*.78:-pace;armL.rotation.x=moving?-pace*.68:-pace*.5;armR.rotation.x=moving?pace*.68:pace*.5;avatar.position.y=moving?Math.abs(Math.sin(t*12))*.05:0;player.position.y=.06}
function updateWorld(delta){const time=clock.getElapsedTime();hubs.forEach((hub,i)=>{hub.userData.orb.position.y=15.75+Math.sin(time*2.1+i)*.3;hub.userData.orb.rotation.y+=delta*1.7;hub.userData.beam.material.opacity=.13+Math.sin(time*1.7+i)*.04});cars.forEach(c=>c.g.position.x=(((time*3.8*c.dir+c.phase*21+42)%76)+76)%76-38);particles.forEach(system=>{const pos=system.point.geometry.attributes.position.array;for(let i=0;i<system.speed.length;i++){pos[i*3+1]-=system.speed[i]*delta;pos[i*3]+=Math.sin(time*.36+i)*.16*delta;if(pos[i*3+1]<.2)pos[i*3+1]=18+Math.random()*6}system.point.geometry.attributes.position.needsUpdate=true})}
function ui(){const p=nearest();state.nearby=p;prompt.classList.toggle('show',!!p);if(p){nearbyText.textContent=p.short;zone.textContent=p.short;mission.textContent=`Explore ${p.short}`}else{zone.textContent=player.position.length()<9?'BASE CAMP':'OPEN WORLD';mission.textContent='Explore the city'}mini.style.left=`${50+player.position.x*1.12}%`;mini.style.top=`${50+player.position.z*1.12}%`}
function render(){requestAnimationFrame(render);const delta=Math.min(clock.getDelta(),.05);if(state.started)updatePlayer(delta);updateWorld(delta);target.lerp(player.position,.075);const offset=new THREE.Vector3(0,19.5,state.cameraDistance).applyAxisAngle(new THREE.Vector3(0,1,0),state.cameraYaw);camera.position.lerp(target.clone().add(offset),.08);camera.lookAt(target.clone().add(new THREE.Vector3(0,1.1,-1.1)));ui();composer.render()}render();
function travel(project){state.destination=project.position.clone().add(project.id==='chrono'?new THREE.Vector3(0,0,6.1):new THREE.Vector3(0,0,-6.1));mission.textContent=`Route set: ${project.short}`;notify(`Route set: ${project.short}`)}
function explore(){if(!state.nearby)return;if(state.nearby.id==='info'){document.querySelector('#infoDialog').showModal();return}if(!document.querySelector('#projectDialog').open)openProject(state.nearby)}

function codingMusic(){const audio={ctx:null,gain:null,timer:null,on:false},notes=[146.83,174.61,220,261.63,293.66,349.23,440],sequence=[0,3,5,2,6,3,4,1,0,4,2,5,6,3,1,4];function beep(f,start,duration,type,volume){const osc=audio.ctx.createOscillator(),env=audio.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(f,start);env.gain.setValueAtTime(.0001,start);env.gain.exponentialRampToValueAtTime(volume,start+.018);env.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(env).connect(audio.gain);osc.start(start);osc.stop(start+duration+.03)}function play(){if(!audio.on)return;const start=audio.ctx.currentTime+.06;sequence.forEach((n,i)=>{const t=start+i*.18;beep(notes[n]*(i%5===0?.5:1),t,.16,'triangle',.045);if(i%4===0)beep(notes[0]*.5,t,.32,'sine',.055);if(i%2)beep(notes[(n+2)%notes.length]*2,t,.055,'square',.012)})}return{async toggle(){if(!audio.ctx){audio.ctx=new AudioContext();audio.gain=audio.ctx.createGain();audio.gain.gain.value=.45;audio.gain.connect(audio.ctx.destination)}audio.on=!audio.on;if(audio.on){await audio.ctx.resume();play();audio.timer=setInterval(play,sequence.length*180)}else{clearInterval(audio.timer);await audio.ctx.suspend()}return audio.on}}}
const music=codingMusic();
window.addEventListener('keydown',e=>{if(e.code==='KeyE')explore();if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code)}});window.addEventListener('keyup',e=>keys.delete(e.code));
canvas.addEventListener('pointerdown',e=>{if(!state.started)return;state.dragging=true;state.pointerX=e.clientX;state.dragDistance=0});window.addEventListener('pointermove',e=>{if(!state.dragging)return;const d=e.clientX-state.pointerX;state.pointerX=e.clientX;state.dragDistance+=Math.abs(d);state.cameraYaw-=d*.006});window.addEventListener('pointerup',e=>{if(!state.dragging||!state.started)return;state.dragging=false;if(state.dragDistance>7)return;pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(clickables,true)[0];if(!hit)return;let o=hit.object;while(o&&!o.userData.project&&!o.userData.place)o=o.parent;if(o?.userData.project||o?.userData.place)travel(o.userData.project||o.userData.place)});canvas.addEventListener('wheel',e=>{state.cameraDistance=THREE.MathUtils.clamp(state.cameraDistance+e.deltaY*.012,19,38)},{passive:true});
document.querySelector('#enterWorld').addEventListener('click',()=>{state.started=true;document.querySelector('#introScreen').classList.add('hidden');notify('Welcome to Antonio’s world')});document.querySelector('.wordmark').addEventListener('click',e=>{e.preventDefault();state.destination=new THREE.Vector3(0,0,6.5)});document.querySelector('#audioToggle').addEventListener('click',async event=>{const control=event.currentTarget;const on=await music.toggle();control.classList.toggle('active',on);control.setAttribute('aria-pressed',String(on));control.querySelector('span').textContent=on?'ON':'OFF';notify(on?'Coding ambience enabled':'Sound paused')});document.querySelector('#openInfo').addEventListener('click',()=>document.querySelector('#infoDialog').showModal());document.querySelector('.close-dialog').addEventListener('click',()=>document.querySelector('#projectDialog').close());document.querySelector('.close-info').addEventListener('click',()=>document.querySelector('#infoDialog').close());document.querySelector('#projectDialog').addEventListener('click',e=>{if(e.target.tagName==='DIALOG')e.currentTarget.close()});document.querySelector('#infoDialog').addEventListener('click',e=>{if(e.target.tagName==='DIALOG')e.currentTarget.close()});document.querySelector('#exploreTouch').addEventListener('click',explore);document.querySelectorAll('[data-dir]').forEach(b=>{const d=b.dataset.dir,start=e=>{e.preventDefault();state.touch.add(d)},end=()=>state.touch.delete(d);b.addEventListener('pointerdown',start);b.addEventListener('pointerup',end);b.addEventListener('pointerleave',end);b.addEventListener('pointercancel',end)});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});
